#!/usr/bin/env python2
##
# The-Password-Manager
# https://github.com/roothaxor
# copyright (c) 2014 RooT HaXor
##
import os, sys, getpass, time
import subprocess, base64
from __files import info, author, version
from random import choice
from string import ascii_lowercase, digits, ascii_uppercase
import clipboard

def nsaview():
	os.system('cls')
	os.system('mode 85,34')
	os.system('title SECURE VAULT - LEVEL 6 CLEARANCE')
	osnfosdnfiodsnfosdinfosin = '''\n
	+------------------------------------------------------------------+
		   ***** Secret material - Level 6 Clearance *****
	  Equivalent to US DOD classification FOUO - For Official Use Only
	+------------------------------------------------------------------+
	\nAll information inside this program requires protection of confidentiality.          Access is restricted by law or regulation to particular groups of people,            Mishandling can incur criminal penalties and loss of respect\n
	'''
	print osnfosdnfiodsnfosdinfosin
	try:
		print "+-------------------+"
		print " Enter Your Password "
		print "+-------------------+"
		adafaczxcvcadfasdasdas = getpass.getpass('# ')
	except KeyboardInterrupt:
		os.system('cls')
		print "\n\n Ahh! Seems like someone forgot the password! eh.."
	itercount = 1
	while adafaczxcvcadfasdasdas != author.ionfdsnfdisncdscnso:
		itercount += 1
		if itercount == 2:
			os.system('cls')
			print "\n\n\n[+] Entering database Attempt no. 2 [+]\n"
		elif itercount == 3:
			os.system('cls')
			print "\n\n\n[+] Attempt no.3, Fail & database file will be Wiped [+]\n"
		elif itercount == 4:
			file = author.filedir
			dst = os.getenv("APPDATA")
			os.system("move "+file+" "+dst)
		adafaczxcvcadfasdasdas = getpass.getpass('Enter Your Pass : ')
	try:
		if (adafaczxcvcadfasdasdas == author.ionfdsnfdisncdscnso):
			try:
				info.ddcrypt()
			except (TypeError, ValueError):
				version.eecrypt()
				print "\nWait a sec.. "
				time.sleep(1)
				info.ddcrypt()
			proc = subprocess.Popen(['more','/C',author.filedir], shell=True)
			proc.wait()
			version.eecrypt()
		elif (adafaczxcvcadfasdasdas == author.panicpassword):
			move = author.filedir
			dst = os.getenv("APPDATA")
			os.system("move "+move+" "+dst)
			os.system('cls')
			print "\n\n\nSystem Breach Protocol inititated ! Database file sent to secure location...."
			print "\n\nYour database is now safely Roaming"+"\n\n"
		else:
			print "\n\n[+] Access Denied [+]"
	except NameError:
		pass

def nsagen():
	os.system('mode 70,19')
	os.system('title Mil Grade Password Generation v.1.2.3')
	banner = '''               
	+----------------------------------------------+
	   Military Grade Password Generation v.1.2.3
	+----------------------------------------------+
	'''
	print banner
	try:
		print "+-----------------------+"
		print "  Reason for the record "
		print "+-----------------------+"
		reason = raw_input('# ')
		print "\n+--------------------+"
		print "  Length ( ie: 10 )"
		print "+--------------------+"
		x = int(raw_input("# "))
	except KeyboardInterrupt:
		os.system('cls')
		print "Exit, Have a good day!"
		sys.exit()
	b =(''.join(choice(ascii_lowercase + digits + ascii_uppercase) for i in range(x)))
	date = time.asctime()
	a = ("Created on " + str(date) + " Reason: " + str(reason))
	info.ddcrypt()
	time.sleep(2)
	with open(author.filedir, "a") as text_file:
	    text_file.write("Pass: " + str(b) + '\n' + a + '\n' + '\n')
	version.eecrypt()
	print "\nRandomly Generated Password "+"for "+reason+" : "+str(b)+"\n"
	clipboard.copy(str(b))
	clipboard.paste()
	print "COPIED TO CLIPBOARD" 
	print "\n[+] Database Encrypted, Closing the program [+]"
	time.sleep(5)

if __name__ == '__main__':
	try:
		if sys.argv[1] == 'view':
			nsaview()
		elif sys.argv[1] == 'generate':
			nsagen()
	except IndexError:
		print "\n\n[+] Unexpected Error, Dayum son! [+]\n\n"